<?php
namespace AppBundle\Repository;
/**
 * LoisirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoisirRepository extends \Doctrine\ORM\EntityRepository
{
  /**
 * Find...
 **/
 public function FindAllLoisirs(){
     $qBuilder = $this
     ->getEntityManager()
     ->createQueryBuilder();
     $qbuilder->select('f');
     $qBuilder->from('AppBundle:Loisir','f');
     
     $result = $qBuilder->getQuery()->getResult();
     
     return $result;
 }
}