<?php

namespace AppBundle\Repository;

/**
 * PassionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassionRepository extends \Doctrine\ORM\EntityRepository
{
}
